# Generated by Django 6.0.8 on 2026-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_cast_profile_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="profile_path",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
