# Generated by Django 6.0.8 on 2026-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
                (
                    "profile_path",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("popularity", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_title", models.CharField(max_length=255)),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("overview", models.TextField()),
                ("poster_path", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "backdrop_path",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("original_language", models.CharField(max_length=20)),
                ("vote_average", models.FloatField(default=0.0)),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(default=0.0)),
                (
                    "casts",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.cast"
                    ),
                ),
            ],
        ),
    ]
