# Generated by Django 6.0.8 on 2026-08-08 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="Watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
