# Generated by Django 6.0.8 on 2026-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_cast_id_alter_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="profile_path",
            field=models.URLField(
                blank=True,
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFDOND67dSQCOxxYJ1XNqiiBk_JOVEvx3iYS5YdrMqea0iFR6L5rFksqQ&s",
                max_length=500,
                null=True,
            ),
        ),
    ]
